<ip>127.0.0.1</ip>
<zoneid>4440176</zoneid>
<zoneip></zoneip>
<country>幻想乡</country>
<login>true</login>
<time>1647057135</time>
<name>弹幕娘</name>
<user>435221170</user>
<user_hash>2d7e96a0</user_hash>
<money>50.00</money>
<face>//i1.hdslb.com/bfs/face/f58c8c14a38c8700d37485852a4b267b5b10f106.jpg</face>
<isadmin>true</isadmin>
<permission><?php echo $AuthLevelString;?></permission>
<level>弹幕抖M <?php echo $AuthLevelString;?></level>
<level_info>{"current_level":5,"current_min":10800,"current_exp":14490,"next_exp":28800}</level_info>
<answer_status>0</answer_status>
<vip>{"vipType":1,"vipDueDate":1626364800000,"dueRemark":"","accessStatus":0,"vipStatus":0,"vipStatusWarn":""}</vip>
<official_verify>{"type":-1,"desc":""}</official_verify>
<block_time>0</block_time>
<lastplaytime>0</lastplaytime>
<lastcid>0</lastcid>
<aid>1</aid>
<bvid></bvid>
<typeid>1</typeid>
<vtype>vupload</vtype>
<oriurl></oriurl>
<suggest_comment>false</suggest_comment>
<server>chat.bilibili.com</server>
<maxlimit></maxlimit>
<chatid><?php echo $ChatId;?></chatid>
<pid>1</pid>
<duration>30:00</duration>
<arctype>Original</arctype>
<allow_bp>false</allow_bp>
<bottom>0</bottom>
<shot>false</shot>
<sinapi>1</sinapi>
<acceptguest>false</acceptguest>
<acceptaccel>false</acceptaccel>
<cache>false</cache>
<broadcast_tcp></broadcast_tcp>
<broadcast_ws></broadcast_ws>
<broadcast_wss></broadcast_wss>
<default_dm>0</default_dm>
<dm_host>0://localhost,1://localhost/rc</dm_host>
<role>0</role>
<has_next>0</has_next>
<online_count>1</online_count>
<dm_mask></dm_mask>
<mask_new></mask_new>
<subtitle>{"allow_submit":true,"lan":"","lan_doc":"","subtitles":[]}</subtitle>
<player_icon></player_icon>
<view_points></view_points>
<is_pay_preview>false</is_pay_preview>
<preview_toast>为创作付费，购买观看完整视频|购买观看</preview_toast>
<interaction></interaction>
<pugv_watch_status>0</pugv_watch_status>
<pugv_pay_status>0</pugv_pay_status>
<pugv_season_status>0</pugv_season_status>
<pcdn></pcdn>
<pcdn_loader>{"flv":{"group":"cg1","labels":{"pcdn_video_type":"flv","pcdn_stage":"release","pcdn_group":"cg1"}},"dash":{"group":"cg1","labels":{"pcdn_video_type":"dash","pcdn_stage":"release","pcdn_group":"cg1"}}}</pcdn_loader>
<options>{"is_360":false,"without_vip":false}</options>
<guide_attention></guide_attention>
<jump_card></jump_card>
<operation_card></operation_card>
<enable_gray_dash_playback>500</enable_gray_dash_playback>
<new_broadcast>1</new_broadcast>
<realtime_dm>1</realtime_dm>
<subtitle_submit_switch>1</subtitle_submit_switch>