<?php
$settings['emoticons'] = array(

    /*
     * You can add more imoticons in this format:
     *
     * "code" => "image.gif",
     *
     */

    // INSERT NEW EMOTICONS BELOW THIS LINE


    // DO NOT EDIT BELOW
    ":!angel:" => "angel.gif",
    ":!bandit:" => "bandit.gif",
    ":!beer:" => "beer.gif",
    ":D" => "bigsmile.gif",
    ":o" => "blush.gif",
    ":!brokenheart:" => "brokenheart.gif",
    ":!bug:" => "bug.gif",
    ":!cake:" => "cake.gif",
    ":!call:" => "call.gif",
    ":!cash:" => "cash.gif",
    ":!clap:" => "clapping.gif",
    ":!coffe:" => "coffe.gif",
    ":!cool:" => "cool.gif",
    ":!cry:" => "crying.gif",
    ":!devil:" => "devil.gif",
    ":!doh:" => "doh.gif",
    ":!drink:" => "drink.gif",
    ":!drunk:" => "drunk.gif",
    ":!dull:" => "dull.gif",
    ":!emo:" => "emo.gif",
    ":!envy:" => "envy.gif",
    ":!evilgrin:" => "evilgrin.gif",
    ":!fubar:" => "fubar.gif",
    ":!giggle:" => "giggle.gif",
    ":!happy:" => "happy.gif",
    ":!headbang:" => "headbang.gif",
    ":!hi:" => "hi.gif",
    ":!inlove:" => "inlove.gif",
    ":!itwasntme:" => "itwasntme.gif",
    ":!kiss:" => "kiss.gif",
    ":!lipssealed:" => "lipssealed.gif",
    ":!mad:" => "mad.gif",
    ":!makeup:" => "makeup.gif",
    ":!mmm:" => "mmm.gif",
    ":!mobile:" => "mobile.gif",
    ":!movie:" => "movie.gif",
    ":!muscle:" => "muscle.gif",
    ":!music:" => "music.gif",
    ":!nerd:" => "nerd.gif",
    ":!nod:" => "nod.gif",
    ":!party:" => "party.gif",
    ":!pizza:" => "pizza.gif",
    ":!puke:" => "puke.gif",
    ":!punch:" => "punch.gif",
    ":!rain:" => "rain.gif",
    ":!rock:" => "rock.gif",
    ":!rofl:" => "rofl.gif",
    ":!sadsmile:" => "sadsmile.gif",
    ":!shake:" => "shake.gif",
    ":!sleepy:" => "sleepy.gif",
    ":)" => "smile.gif",
    ":!smirk:" => "smirk.gif",
    ":!smoke:" => "smoke.gif",
    ":!speechless:" => "speechless.gif",
    ":!sun:" => "sun.gif",
    ":!surprised:" => "surprised.gif",
    ":!swear:" => "swear.gif",
    ":!sweating:" => "sweating.gif",
    ":!talking:" => "talking.gif",
    ":!thinking:" => "thinking.gif",
    ":!time:" => "time.gif",
    ":!tmi:" => "tmi.gif",
    ":p" => "tongueout.gif",
    ":!wait:" => "wait.gif",
    ":!whew:" => "whew.gif",
    ";)" => "wink.gif",
    ":!wondering:" => "wondering.gif",
    ":!worried:" => "worried.gif",
    ":!yawn:" => "yawn.gif",
);